### ISSUE TITLE
Define Zygote adjoint of `create_array`

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/SymbolicUtils.jl#274]
I think this is the more robust solution to https://github.com/SciML/DataDrivenDiffEq.jl/issues/54.

I'm open to adding this patch behind a `@requires`.

cc @DhairyaLGandhi

**Comment by ChrisRackauckas** [comment]
Why not just depend on ChainRulesCore.jl? That's a tiny and common dependency. I don't think rules will ever need `@requires` unless they are for a higher order function.

**Comment by shashi** [comment]
Okay yeah that works too.

**Comment by doddgray** [comment]
Isn't the main Zygote blocker the mutation in `_create_array` and `typed_vhcat`?

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/f55b96e2b6a135c31fa95347e61b3313c4b9ba7e/src/code.jl#L384-L391

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/f55b96e2b6a135c31fa95347e61b3313c4b9ba7e/src/code.jl#L427-L438

Constructing these arrays as  `Zygote.Buffer`s or wrapping `_create_array` calls in `Zygote.forwarddiff` could work but requires heavier dependencies than ChainRulesCore.jl. 

Is this mutating array construction approach necessary or just chosen because the `elems` arrive as a tuple? Something like `copy(reshape([elems...],dims))` might produce the same array without angering Zygote. 

Zygote and ChainRules already have rules for `Type{<:Matrix}` construction with `hvcat`, and with a minor tweak the previous `create_array(::Type{<:Matrix}` methods became Zygote-friendly (ref https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/270)

For higher dimensional arrays my current workaround is to convert `Array{Num}`s to `SArray`s before passing them through the function generation machinery in SymbolicUtils.jl and Symbolics.jl, like this
```julia
using StaticArrays
using ChainRulesCore
using Zygote
using Symbolics: Num, make_array, SerialForm, Func, toexpr, _build_and_inject_function, @variables
using RuntimeGeneratedFunctions: @__MODULE__, init
init(@__MODULE__)
# generic rrules for StaticArray construction, might also want these for SVector and SMatrix
ChainRulesCore.rrule(T::Type{<:SArray}, xs::Number...) = ( T(xs...), dv -> (NO_FIELDS, dv...) )
ChainRulesCore.rrule(T::Type{<:SArray}, x::AbstractArray) = ( T(x), dv -> (NO_FIELDS, dv) )

# hacky methods bypassing Symbolics.build_function to explicitly specify `SArray` in `make_array`
function generate_array_fn(args::Vector{Num},A::SArray; expr_module=@__MODULE__(), parallel=SerialForm())
	return fn = _build_and_inject_function(expr_module,toexpr(Func(args,[],make_array(parallel,args,A,SArray))))
end

function generate_array_fn(arg::Num,A::SArray; expr_module=@__MODULE__(), parallel=SerialForm())
	return fn = generate_array_fn([arg,], A; expr_module, parallel)
end

function generate_A_fn()
	@variables a
	A	= 		cat(	[	a  	0	0
						0   	2*a	0
						0	0	3*a	],
					[	a^2  0	0
						0   sin(a)  0
						0	0	3.3	],
						dims=3,
			)
	return f_A = generate_array_fn(a,SArray{Tuple{3,3,2}}(A))
end
```

In this case `create_array` dispatches on `Type{<:SArray}`, and Zygote works happily with the `SArray` constructor `rrule`s
```julia
julia> f_A = generate_A_fn()
RuntimeGeneratedFunction(#=in Main=#, #=using Main=#, :((a,)->begin
          #= /home/dodd/.julia/packages/SymbolicUtils/fikCA/src/code.jl:282 =#
          #= /home/dodd/.julia/packages/SymbolicUtils/fikCA/src/code.jl:283 =#
          begin
              #= /home/dodd/.julia/packages/SymbolicUtils/fikCA/src/code.jl:374 =#
              (SymbolicUtils.Code.create_array)(SArray, nothing, Val{(3, 3, 2)}(), a, 0, 0, 0, (*)(2, a), 0, 0, 0, (*)(3, a), (^)(a, 2), 0, 0, 0, (sin)(a), 0, 0, 0, 3.3)
          end
      end))

julia> f_A(0.3)   #   3×3×2 SArray{Tuple{3, 3, 2}, Float64, 3, 18} with indices SOneTo(3)×SOneTo(3)×SOneTo(2):
# [:, :, 1] =
# 0.3  0.0  0.0
# 0.0  0.6  0.0
# 0.0  0.0  0.9
# [:, :, 2] =
# 0.09  0.0      0.0
# 0.0   0.29552  0.0
# 0.0   0.0      3.3

julia> Zygote.gradient(x->sum(f_A(x)),0.3)     #   (7.555336489125606,)
```

**Comment by doddgray** [comment]
I meant to say, getting Zygote compatibility via `SArray` conversion is probably not a reasonable solution for large Arrays, and as written above requires knowing the Array dimensions when converting, also bad.

**Comment by shashi** [comment]
> Isn't the main Zygote blocker the mutation in _create_array and typed_vhcat?

I think if we add adjoint for `create_array` which probably will be trivial then both of those functions will never be looked up for adjoint because they are internal to create_array.

**Comment by DhairyaLGandhi** [comment]
Presumably we only want the gradient just for the `elems` here, so this should be more efficient than `typed_hvcat` I think.
